"""Gemini-compatible JSON Schema cleaning.

Gemini's ``FunctionDeclaration`` rejects extra JSON Schema fields that
are common in OpenAPI / MCP tool definitions (``$schema``,
``additionalProperties``, ``default``, ``title``).  This module
provides a recursive cleaner that strips unsupported fields while
preserving the structure Gemini expects.

Pydantic / FastAPI tool generators render ``Optional[X]`` parameters as
``{"anyOf": [{"type": X}, {"type": "null"}]}``. Naively stripping
``anyOf`` (because it is not in the allowed-key list) leaves the
property with no type at all — Gemini then silently refuses to invoke
the tool. This module collapses that pattern (and similar ``oneOf`` /
``allOf`` shapes) to ``{"type": X, "nullable": True}`` before stripping
unknown keys, so MCP tools generated by Pydantic round-trip cleanly
into Gemini Live function declarations.

The same optionality also arrives as a plain type list — ``{"type":
["string", "null"]}`` — which is what JSON Schema itself says and what
non-Pydantic generators emit (a TypeScript MCP server going through
``zod-to-json-schema``, for one). ``type`` is a key Gemini accepts, so
that list used to survive the cleaning untouched and fail inside
``FunctionDeclaration``, whose ``type`` is a single-valued enum. It is
folded down the same way, so both spellings of "optional string" reach
Gemini as one.
"""

from __future__ import annotations

from typing import Any

# Fields that Gemini accepts in a function parameter schema.
_GEMINI_ALLOWED_KEYS = frozenset(
    {
        "type",
        "properties",
        "required",
        "description",
        "enum",
        "items",
        "format",
        "nullable",
        "minimum",
        "maximum",
        "minItems",
        "maxItems",
    }
)


def clean_gemini_schema(schema: dict[str, Any] | None) -> dict[str, Any] | None:
    """Recursively prepare a JSON Schema for Gemini ``FunctionDeclaration``.

    Performs two passes per node:

    1. **Collapse Pydantic-style Optionals.** ``{"anyOf": [{...}, {"type":
       "null"}]}`` becomes ``{..., "nullable": true}``. ``oneOf`` /
       ``allOf`` are handled the same way for symmetry. When the union
       has multiple non-null branches, we keep the first one and add
       ``nullable`` if any branch was null — Gemini's schema dialect
       does not support full union types.
    2. **Strip unknown keys.** Anything not in :data:`_GEMINI_ALLOWED_KEYS`
       (e.g. ``$schema``, ``additionalProperties``, ``default``, ``title``)
       is dropped at every nesting level.

    Args:
        schema: A JSON Schema dict (e.g. tool parameter schema), or None.

    Returns:
        A cleaned copy, or None if input was None.
    """
    if schema is None:
        return None
    return _clean(schema)


def _collapse_union(obj: dict[str, Any]) -> dict[str, Any]:
    """If *obj* is a union schema, fold it down to a single branch.

    Handles ``anyOf``, ``oneOf``, ``allOf``. ``Optional[X]`` (the
    Pydantic shape ``[{type: X}, {type: null}]``) collapses to
    ``{type: X, nullable: True}``. Wider unions keep the first
    non-null branch and mark ``nullable`` if any branch was null.
    """
    union_key = next(
        (k for k in ("anyOf", "oneOf", "allOf") if k in obj and isinstance(obj[k], list)),
        None,
    )
    if union_key is None:
        return obj

    branches: list[dict[str, Any]] = [b for b in obj[union_key] if isinstance(b, dict)]
    has_null = any(b.get("type") == "null" for b in branches)
    non_null = [b for b in branches if b.get("type") != "null"]

    if not non_null:
        # Pure null union → fall back to a string nullable so the
        # property remains valid; should not happen in practice.
        merged: dict[str, Any] = {"type": "string", "nullable": True}
    else:
        # First non-null branch wins. Merge in description + nullable.
        merged = dict(non_null[0])
        if has_null:
            merged["nullable"] = True

    # Preserve description / other allowed keys from the parent.
    for key in ("description", "title"):
        if key in obj and key not in merged:
            merged[key] = obj[key]
    return merged


def _collapse_type_list(obj: dict[str, Any]) -> dict[str, Any]:
    """Fold a JSON Schema type *list* down to the single type Gemini takes.

    ``{"type": ["string", "null"]}`` is how JSON Schema spells an optional
    string, and Gemini's ``type`` is a single-valued enum — so the list has to
    become ``{"type": "string", "nullable": True}`` here or fail validation
    inside ``FunctionDeclaration``. Wider lists keep their first non-null
    member, matching how :func:`_collapse_union` treats a wider ``anyOf``:
    Gemini's dialect has no union type either way.
    """
    types_ = obj.get("type")
    if not isinstance(types_, list):
        return obj

    named = [t for t in types_ if isinstance(t, str)]
    non_null = [t for t in named if t != "null"]

    collapsed = dict(obj)
    # An all-null list would leave the property with no type at all, which is
    # what Gemini silently refuses to invoke; string keeps it declarable.
    collapsed["type"] = non_null[0] if non_null else "string"
    if len(named) != len(non_null):
        collapsed["nullable"] = True
    return collapsed


def _clean(obj: dict[str, Any]) -> dict[str, Any]:
    # Collapse union shapes BEFORE stripping unknown keys, so the union
    # members get inspected rather than silently discarded.
    obj = _collapse_union(obj)
    # And the type-list spelling of the same thing, which survives the strip
    # untouched (``type`` is allowed) and would fail inside Gemini's own model.
    obj = _collapse_type_list(obj)

    result: dict[str, Any] = {}
    for key, value in obj.items():
        if key not in _GEMINI_ALLOWED_KEYS:
            continue
        if key == "properties" and isinstance(value, dict):
            result[key] = {k: _clean(v) for k, v in value.items() if isinstance(v, dict)}
        elif key == "items" and isinstance(value, dict):
            result[key] = _clean(value)
        else:
            result[key] = value
    return result
