"""Characters a model reads as an ASCII letter, digit or mark, and those
that read as several letters: generated by ``scripts/build_lookalikes.py``
from Unicode's confusables.txt (UTS #39, version 18.0.0), the
compatibility and canonical forms of Unicode 15.1.0
(NFKC with case folding, accented letters) and the script's own list of
what UTS #39 does not hold. Do not edit; run the script again.

The data is derived from Unicode data files, under this notice:

UNICODE LICENSE V3

COPYRIGHT AND PERMISSION NOTICE

Copyright (c) 1991-2026 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.

IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.
"""

from __future__ import annotations

CONFUSABLES_VERSION = "18.0.0"
CONFUSABLES_SHA256 = "6ed3ee967c9dfdf6677d563c9985182fbc50a2efb7d6059cd57b2e2ce18f5b92"
UNICODE_VERSION = "15.1.0"

FORMS: dict[str, str] = {
    "\u0022": (
        "\u02ba\u02dd\u02ee\u02f6\u05f2\u05f4\u1cd3\u201c\u201d\u201f\u2033\u2036\u3003\uff02"
    ),
    "'": (
        "`\u00b4\u02b9\u02bb\u02bc\u02bd\u02be\u02c8\u02ca\u02cb\u02f4\u0384"
        "\u055a\u055b\u055d\u05d9\u05f3\u07f4\u07f5\u144a\u16cc\u1fbd\u1fbf\u1ffe"
        "\u2018\u2019\u201b\u2032\u2035\u2cff\ua78b\ua78c\uff07\uff40\U00016f51"
        "\U00016f52\U0001e94b"
    ),
    "/": (
        "\u1735\u2041\u2044\u2215\u2571\u27cb\u29f8\u2cc6\u2cc7\u2f03\u3033\u30ce"
        "\u31d2\u31d3\u4e3f\uff0f\uff89\U0001d23a"
    ),
    "0": ("\u2070\u2080\u24ea\uff10\U0001d7ce\U0001d7d8\U0001d7e2\U0001d7ec\U0001d7f6\U0001fbf0"),
    "1": ("\u00b9\u2081\u2460\uff11\U0001d7cf\U0001d7d9\U0001d7e3\U0001d7ed\U0001d7f7\U0001fbf1"),
    "2": (
        "\u00b2\u01a7\u03e8\u10c7\u14bf\u1616\u1cb7\u2082\u2461\ua644\ua6ef\ua75a"
        "\uff12\U0001ccf2\U0001d7d0\U0001d7da\U0001d7e4\U0001d7ee\U0001d7f8"
        "\U0001fbf2"
    ),
    "3": (
        "\u00b3\u01b7\u021c\u0417\u04e0\u0545\u0969\u0ae9\u1702\u1c95\u2083\u2462"
        "\u2c9c\u2cc4\u2ccc\ua76a\ua7ab\uff13\U000118ca\U00016f3b\U0001ccf3"
        "\U0001d206\U0001d7d1\U0001d7db\U0001d7e5\U0001d7ef\U0001d7f9\U0001fbf3"
    ),
    "4": (
        "\u13ce\u2074\u2084\u2463\uab9e\uff14\U000118af\U00016e82\U0001ccf4"
        "\U0001d7d2\U0001d7dc\U0001d7e6\U0001d7f0\U0001d7fa\U0001fbf4"
    ),
    "5": (
        "\u01bc\u2075\u2085\u2464\uff15\U000118bb\U0001ccf5\U0001d7d3\U0001d7dd"
        "\U0001d7e7\U0001d7f1\U0001d7fb\U0001fbf5"
    ),
    "6": (
        "\u03ec\u0431\u13ee\u2076\u2086\u2465\u2cd2\u2cd3\u2cdc\ua543\uabbe\uff16"
        "\U000118d5\U0001ccf6\U0001d7d4\U0001d7de\U0001d7e8\U0001d7f2\U0001d7fc"
        "\U0001fbf6"
    ),
    "7": (
        "\u172a\u1c84\u2077\u2087\u2466\uff17\U000104d2\U000118c6\U00016e8a"
        "\U0001ccf7\U0001d1fe\U0001d212\U0001d7d5\U0001d7df\U0001d7e9\U0001d7f3"
        "\U0001d7fd\U0001fbf7"
    ),
    "8": (
        "\u0222\u0223\u09ea\u0a6a\u0b03\u2078\u2088\u2467\ua589\uff18\U0001031a"
        "\U00011445\U000169fe\U0001ccf8\U0001d7d6\U0001d7e0\U0001d7ea\U0001d7f4"
        "\U0001d7fe\U0001e8cb\U0001fbf8"
    ),
    "9": (
        "\u09ed\u0a67\u0b68\u0d6d\u2079\u2089\u2468\u2cca\u2ccb\ua76e\ua76f\uff19"
        "\U000118ac\U000118cc\U000118d6\U000169c1\U0001ccf9\U0001d7d7\U0001d7e1"
        "\U0001d7eb\U0001d7f5\U0001d7ff\U0001e2f2\U0001fbf9"
    ),
    ":": (
        "\u02d0\u02f8\u0589\u05c3\u0703\u0704\u0831\u0903\u0a83\u1361\u1393\u16ec"
        "\u1803\u1809\u205a\u2236\ua4fd\ua789\ufe13\ufe30\ufe55\uff1a\U0001015b"
        "\U00010af5\U00011002\U00011082\U00011182\U0001123a\U000115be\U000116ac"
        "\U00011838\U00011dd9\U0001d108"
    ),
    "<": (
        "\u02c2\u1438\u16b2\u2039\u2329\u276e\u27e8\u2d66\u3008\ufe3f\ufe64\uff1c"
        "\U0001032d\U00016aec\U0001d236"
    ),
    ">": ("\u02c3\u1433\u203a\u232a\u276f\u27e9\u3009\ufe40\ufe65\uff1e\U00016f3f\U0001d237"),
    "_": ("\u0640\u07fa\ufe33\ufe34\ufe4d\ufe4e\ufe4f\uff3f\U000145c1"),
    "a": (
        "\u00aa\u00c0\u00c1\u00c2\u00c3\u00c4\u00c5\u00e0\u00e1\u00e2\u00e3\u00e4"
        "\u00e5\u0100\u0101\u0102\u0103\u0104\u0105\u01cd\u01ce\u01de\u01df\u01e0"
        "\u01e1\u01fa\u01fb\u0200\u0201\u0202\u0203\u0226\u0227\u0251\u0391\u03b1"
        "\u0410\u0430\u13aa\u15c5\u1d00\u1d2c\u1d43\u1e00\u1e01\u1ea0\u1ea1\u1ea2"
        "\u1ea3\u1ea4\u1ea5\u1ea6\u1ea7\u1ea8\u1ea9\u1eaa\u1eab\u1eac\u1ead\u1eae"
        "\u1eaf\u1eb0\u1eb1\u1eb2\u1eb3\u1eb4\u1eb5\u1eb6\u1eb7\u2090\u212b\u237a"
        "\u24b6\u24d0\ua4ee\uab64\uab7a\uff21\uff41\U000102a0\U00016f40\U0001ccd6"
        "\U0001d400\U0001d41a\U0001d434\U0001d44e\U0001d468\U0001d482\U0001d49c"
        "\U0001d4b6\U0001d4d0\U0001d4ea\U0001d504\U0001d51e\U0001d538\U0001d552"
        "\U0001d56c\U0001d586\U0001d5a0\U0001d5ba\U0001d5d4\U0001d5ee\U0001d608"
        "\U0001d622\U0001d63c\U0001d656\U0001d670\U0001d68a\U0001d6a8\U0001d6c2"
        "\U0001d6e2\U0001d6fc\U0001d71c\U0001d736\U0001d756\U0001d770\U0001d790"
        "\U0001d7aa\U0001df5a\U0001df6a\U0001f130"
    ),
    "b": (
        "\u0184\u0299\u0392\u0412\u042c\u0432\u044c\u07d5\u13cf\u13f4\u13fc\u1472"
        "\u15af\u15f7\u1d2e\u1d47\u1e02\u1e03\u1e04\u1e05\u1e06\u1e07\u212c\u24b7"
        "\u24d1\u2c82\u2c83\ua4d0\ua557\ua69d\ua7b4\uff22\uff42\U00010282"
        "\U000102a1\U00010301\U0001031c\U00010784\U00016eb6\U0001ccd7\U0001d207"
        "\U0001d401\U0001d41b\U0001d435\U0001d44f\U0001d469\U0001d483\U0001d4b7"
        "\U0001d4d1\U0001d4eb\U0001d505\U0001d51f\U0001d539\U0001d553\U0001d56d"
        "\U0001d587\U0001d5a1\U0001d5bb\U0001d5d5\U0001d5ef\U0001d609\U0001d623"
        "\U0001d63d\U0001d657\U0001d671\U0001d68b\U0001d6a9\U0001d6e3\U0001d71d"
        "\U0001d757\U0001d791\U0001f131"
    ),
    "c": (
        "\u00c7\u00e7\u0106\u0107\u0108\u0109\u010a\u010b\u010c\u010d\u03f2\u03f9"
        "\u0421\u0441\u1004\u105a\u13df\u1c83\u1d04\u1d9c\u1e08\u1e09\u2102\u212d"
        "\u216d\u217d\u24b8\u24d2\u2ca4\u2ca5\ua4da\ua7f2\uabaf\uff23\uff43"
        "\U000102a2\U00010302\U00010415\U0001043d\U0001051b\U000118e9\U000118f2"
        "\U0001ccd8\U0001d134\U0001d402\U0001d41c\U0001d436\U0001d450\U0001d46a"
        "\U0001d484\U0001d49e\U0001d4b8\U0001d4d2\U0001d4ec\U0001d520\U0001d554"
        "\U0001d56e\U0001d588\U0001d5a2\U0001d5bc\U0001d5d6\U0001d5f0\U0001d60a"
        "\U0001d624\U0001d63e\U0001d658\U0001d672\U0001d68c\U0001f12b\U0001f132"
        "\U0001f74c"
    ),
    "d": (
        "\u010e\u010f\u0501\u13a0\u13e7\u146f\u15de\u15ea\u1d05\u1d30\u1d48\u1e0a"
        "\u1e0b\u1e0c\u1e0d\u1e0e\u1e0f\u1e10\u1e11\u1e12\u1e13\u2145\u2146\u216e"
        "\u217e\u24b9\u24d3\ua4d2\ua4d3\uab70\uff24\uff44\U0001018b\U0001ccd9"
        "\U0001d403\U0001d41d\U0001d437\U0001d451\U0001d46b\U0001d485\U0001d49f"
        "\U0001d4b9\U0001d4d3\U0001d4ed\U0001d507\U0001d521\U0001d53b\U0001d555"
        "\U0001d56f\U0001d589\U0001d5a3\U0001d5bd\U0001d5d7\U0001d5f1\U0001d60b"
        "\U0001d625\U0001d63f\U0001d659\U0001d673\U0001d68d\U0001f133"
    ),
    "e": (
        "\u00c8\u00c9\u00ca\u00cb\u00e8\u00e9\u00ea\u00eb\u0112\u0113\u0114\u0115"
        "\u0116\u0117\u0118\u0119\u011a\u011b\u0204\u0205\u0206\u0207\u0228\u0229"
        "\u0395\u0415\u0435\u04bd\u13ac\u1d07\u1d31\u1d49\u1e14\u1e15\u1e16\u1e17"
        "\u1e18\u1e19\u1e1a\u1e1b\u1e1c\u1e1d\u1eb8\u1eb9\u1eba\u1ebb\u1ebc\u1ebd"
        "\u1ebe\u1ebf\u1ec0\u1ec1\u1ec2\u1ec3\u1ec4\u1ec5\u1ec6\u1ec7\u2091\u212e"
        "\u212f\u2130\u2147\u22ff\u24ba\u24d4\u2d39\ua4f0\ua5cb\uab32\uab7c\uff25"
        "\uff45\U00010286\U000118a6\U000118ae\U0001ccda\U0001d404\U0001d41e"
        "\U0001d438\U0001d452\U0001d46c\U0001d486\U0001d4d4\U0001d4ee\U0001d508"
        "\U0001d522\U0001d53c\U0001d556\U0001d570\U0001d58a\U0001d5a4\U0001d5be"
        "\U0001d5d8\U0001d5f2\U0001d60c\U0001d626\U0001d640\U0001d65a\U0001d674"
        "\U0001d68e\U0001d6ac\U0001d6e6\U0001d720\U0001d75a\U0001d794\U0001df81"
        "\U0001f134"
    ),
    "f": (
        "\u017f\u0192\u0284\u03dc\u0584\u07d3\u15b4\u1da0\u1e1e\u1e1f\u1e9d\u2131"
        "\u24bb\u24d5\ua4dd\ua730\ua798\ua799\ua7f3\uab35\uff26\uff46\U0001017e"
        "\U00010287\U000102a5\U00010525\U000118a2\U000118c2\U0001ccdb\U0001d213"
        "\U0001d405\U0001d41f\U0001d439\U0001d453\U0001d46d\U0001d487\U0001d4bb"
        "\U0001d4d5\U0001d4ef\U0001d509\U0001d523\U0001d53d\U0001d557\U0001d571"
        "\U0001d58b\U0001d5a5\U0001d5bf\U0001d5d9\U0001d5f3\U0001d60d\U0001d627"
        "\U0001d641\U0001d65b\U0001d675\U0001d68f\U0001d7ca\U0001f135"
    ),
    "g": (
        "\u011c\u011d\u011e\u011f\u0120\u0121\u0122\u0123\u018d\u01e6\u01e7\u01f4"
        "\u01f5\u0261\u0262\u050c\u050d\u0581\u13c0\u13f3\u13fb\u1d33\u1d4d\u1d83"
        "\u1e20\u1e21\u210a\u24bc\u24d6\ua4d6\uab90\uff27\uff47\U00010792"
        "\U0001ccdc\U0001d406\U0001d420\U0001d43a\U0001d454\U0001d46e\U0001d488"
        "\U0001d4a2\U0001d4d6\U0001d4f0\U0001d50a\U0001d524\U0001d53e\U0001d558"
        "\U0001d572\U0001d58c\U0001d5a6\U0001d5c0\U0001d5da\U0001d5f4\U0001d60e"
        "\U0001d628\U0001d642\U0001d65c\U0001d676\U0001d690\U0001f136"
    ),
    "h": (
        "\u0124\u0125\u021e\u021f\u029c\u02b0\u0397\u041d\u043d\u04ba\u04bb\u0570"
        "\u10b9\u13bb\u13c2\u157c\u1d34\u1e22\u1e23\u1e24\u1e25\u1e26\u1e27\u1e28"
        "\u1e29\u1e2a\u1e2b\u1e96\u2095\u210b\u210c\u210d\u210e\u24bd\u24d7\u2c8e"
        "\u2c8f\ua4e7\uab8b\uff28\uff48\U000102cf\U00010796\U0001ccdd\U0001d407"
        "\U0001d421\U0001d43b\U0001d46f\U0001d489\U0001d4bd\U0001d4d7\U0001d4f1"
        "\U0001d525\U0001d559\U0001d573\U0001d58d\U0001d5a7\U0001d5c1\U0001d5db"
        "\U0001d5f5\U0001d60f\U0001d629\U0001d643\U0001d65d\U0001d677\U0001d691"
        "\U0001d6ae\U0001d6e8\U0001d722\U0001d75c\U0001d796\U0001f137"
    ),
    "i": (
        "\u00a1\u00cc\u00cd\u00ce\u00cf\u00ec\u00ed\u00ee\u00ef\u0128\u0129\u012a"
        "\u012b\u012c\u012d\u012e\u012f\u0130\u0131\u01cf\u01d0\u0208\u0209\u020a"
        "\u020b\u0269\u026a\u03b9\u0456\u04c0\u04cf\u0582\u13a5\u1d35\u1d62\u1e2c"
        "\u1e2d\u1e2e\u1e2f\u1ec8\u1ec9\u1eca\u1ecb\u2071\u2110\u2111\u2139\u2148"
        "\u2160\u2170\u2373\u24be\u24d8\u2c93\ua647\uab75\uff29\uff49\U000118c3"
        "\U0001d408\U0001d422\U0001d43c\U0001d456\U0001d470\U0001d48a\U0001d4be"
        "\U0001d4d8\U0001d4f2\U0001d526\U0001d540\U0001d55a\U0001d574\U0001d58e"
        "\U0001d5a8\U0001d5c2\U0001d5dc\U0001d5f6\U0001d610\U0001d62a\U0001d644"
        "\U0001d65e\U0001d678\U0001d692\U0001d6a4\U0001d6ca\U0001d704\U0001d73e"
        "\U0001d778\U0001d7b2\U0001e050\U0001f138"
    ),
    "j": (
        "\u0134\u0135\u01f0\u0237\u02b2\u037f\u03f3\u0408\u0458\u0575\u13ab\u148d"
        "\u1d0a\u1d36\u2149\u24bf\u24d9\u2c7c\ua4d9\ua7b2\uab7b\uff2a\uff4a"
        "\U0001ccdf\U0001d409\U0001d423\U0001d43d\U0001d457\U0001d471\U0001d48b"
        "\U0001d4a5\U0001d4bf\U0001d4d9\U0001d4f3\U0001d50d\U0001d527\U0001d541"
        "\U0001d55b\U0001d575\U0001d58f\U0001d5a9\U0001d5c3\U0001d5dd\U0001d5f7"
        "\U0001d611\U0001d62b\U0001d645\U0001d65f\U0001d679\U0001d693\U0001d6a5"
        "\U0001f139"
    ),
    "k": (
        "\u0136\u0137\u01e8\u01e9\u039a\u03ba\u03f0\u041a\u043a\u13e6\u16d5\u1d0b"
        "\u1d37\u1d4f\u1e30\u1e31\u1e32\u1e33\u1e34\u1e35\u2096\u212a\u24c0\u24da"
        "\u2c94\ua4d7\uff2b\uff4b\U00010518\U0001cce0\U0001d40a\U0001d424"
        "\U0001d43e\U0001d458\U0001d472\U0001d48c\U0001d4a6\U0001d4c0\U0001d4da"
        "\U0001d4f4\U0001d50e\U0001d528\U0001d542\U0001d55c\U0001d576\U0001d590"
        "\U0001d5aa\U0001d5c4\U0001d5de\U0001d5f8\U0001d612\U0001d62c\U0001d646"
        "\U0001d660\U0001d67a\U0001d694\U0001d6b1\U0001d6cb\U0001d6de\U0001d6eb"
        "\U0001d705\U0001d718\U0001d725\U0001d73f\U0001d752\U0001d75f\U0001d779"
        "\U0001d78c\U0001d799\U0001d7b3\U0001d7c6\U0001e039\U0001e05a\U0001f13a"
    ),
    "l": (
        "1I|\u0139\u013a\u013b\u013c\u013d\u013e\u0196\u01c0\u029f\u02e1\u0399"
        "\u0406\u04c0\u04cf\u053c\u05c0\u05d5\u05df\u0627\u0661\u06f1\u07ca\u0964"
        "\u104a\u13de\u14aa\u16c1\u16d0\u1d38\u1dab\u1e36\u1e37\u1e38\u1e39\u1e3a"
        "\u1e3b\u1e3c\u1e3d\u2097\u2110\u2111\u2112\u2113\u2160\u216c\u217c\u21bf"
        "\u2223\u23fd\u24c1\u24db\u2502\u2503\u2c92\u2cd0\u2cd1\u2d4a\u2d4f\ua4e1"
        "\ua4f2\ua56f\ua781\ua7ae\ua7fe\ua830\ua8ce\uaa5d\uabae\ufe31\ufe8d\ufe8e"
        "\uff11\uff29\uff2c\uff4c\uff5c\uffe8\U0001028a\U00010309\U00010320"
        "\U0001041b\U00010443\U0001050e\U00010526\U00010926\U00010c3e\U00010ca5"
        "\U00010cfa\U00011047\U000110c0\U00011141\U000111c5\U000113d4\U0001144b"
        "\U000115c5\U00011641\U000118a3\U000118b2\U00011c41\U00011dda\U00011de1"
        "\U00016d63\U00016eaa\U00016f16\U00016f28\U0001ccde\U0001cce1\U0001ccf1"
        "\U0001d100\U0001d22a\U0001d377\U0001d408\U0001d40b\U0001d425\U0001d43c"
        "\U0001d43f\U0001d459\U0001d470\U0001d473\U0001d48d\U0001d4c1\U0001d4d8"
        "\U0001d4db\U0001d4f5\U0001d50f\U0001d529\U0001d540\U0001d543\U0001d55d"
        "\U0001d574\U0001d577\U0001d591\U0001d5a8\U0001d5ab\U0001d5c5\U0001d5dc"
        "\U0001d5df\U0001d5f9\U0001d610\U0001d613\U0001d62d\U0001d644\U0001d647"
        "\U0001d661\U0001d678\U0001d67b\U0001d695\U0001d6b0\U0001d6ea\U0001d724"
        "\U0001d75e\U0001d798\U0001d7cf\U0001d7d9\U0001d7e3\U0001d7ed\U0001d7f7"
        "\U0001e141\U0001e8c7\U0001ed01\U0001ee00\U0001ee80\U0001f13b\U0001fbf1"
    ),
    "m": (
        "\u039c\u03fa\u041c\u043c\u13b7\u15f0\u16d6\u1d0d\u1d39\u1d50\u1e3e\u1e3f"
        "\u1e40\u1e41\u1e42\u1e43\u2098\u2133\u216f\u217f\u24c2\u24dc\u2c98\ua4df"
        "\uff2d\uff4d\U000102b0\U00010311\U00010c21\U0001cce2\U0001d40c\U0001d426"
        "\U0001d440\U0001d45a\U0001d474\U0001d48e\U0001d4c2\U0001d4dc\U0001d4f6"
        "\U0001d510\U0001d52a\U0001d544\U0001d55e\U0001d578\U0001d592\U0001d5ac"
        "\U0001d5c6\U0001d5e0\U0001d5fa\U0001d614\U0001d62e\U0001d648\U0001d662"
        "\U0001d67c\U0001d696\U0001d6b3\U0001d6ed\U0001d727\U0001d761\U0001d79b"
        "\U0001e03b\U0001f13c"
    ),
    "n": (
        "\u00d1\u00f1\u0143\u0144\u0145\u0146\u0147\u0148\u01f8\u01f9\u0274\u039d"
        "\u0578\u057c\u1d3a\u1db0\u1e44\u1e45\u1e46\u1e47\u1e48\u1e49\u1e4a\u1e4b"
        "\u207f\u2099\u2115\u24c3\u24dd\u2c9a\u2c9b\ua4e0\uff2e\uff4e\U00010513"
        "\U00011abe\U0001cce3\U0001d40d\U0001d427\U0001d441\U0001d45b\U0001d475"
        "\U0001d48f\U0001d4a9\U0001d4c3\U0001d4dd\U0001d4f7\U0001d511\U0001d52b"
        "\U0001d55f\U0001d579\U0001d593\U0001d5ad\U0001d5c7\U0001d5e1\U0001d5fb"
        "\U0001d615\U0001d62f\U0001d649\U0001d663\U0001d67d\U0001d697\U0001d6b4"
        "\U0001d6ee\U0001d728\U0001d762\U0001d79c\U0001f13d"
    ),
    "o": (
        "0\u00ba\u00d2\u00d3\u00d4\u00d5\u00d6\u00f2\u00f3\u00f4\u00f5\u00f6"
        "\u014c\u014d\u014e\u014f\u0150\u0151\u01a0\u01a1\u01d1\u01d2\u01ea\u01eb"
        "\u01ec\u01ed\u020c\u020d\u020e\u020f\u022a\u022b\u022c\u022d\u022e\u022f"
        "\u0230\u0231\u039f\u03bf\u03c3\u03ed\u041e\u043e\u0555\u0585\u05e1\u0647"
        "\u0665\u06be\u06c1\u06d5\u06f5\u07c0\u07cb\u0840\u0966\u09e6\u0a66\u0ae6"
        "\u0b20\u0b66\u0be6\u0c02\u0c66\u0c82\u0ce6\u0d02\u0d20\u0d66\u0d82\u0e50"
        "\u0ed0\u101d\u1040\u10ff\u110b\u11bc\u12d0\u17e0\u1a45\u1a80\u1a90\u1bea"
        "\u1c82\u1cbf\u1d0f\u1d11\u1d3c\u1d52\u1e4c\u1e4d\u1e4e\u1e4f\u1e50\u1e51"
        "\u1e52\u1e53\u1ecc\u1ecd\u1ece\u1ecf\u1ed0\u1ed1\u1ed2\u1ed3\u1ed4\u1ed5"
        "\u1ed6\u1ed7\u1ed8\u1ed9\u1eda\u1edb\u1edc\u1edd\u1ede\u1edf\u1ee0\u1ee1"
        "\u1ee2\u1ee3\u2092\u2134\u24c4\u24de\u2c9e\u2c9f\u2d54\u3007\u3147\ua4f3"
        "\uab3d\ufba6\ufba7\ufba8\ufba9\ufbaa\ufbab\ufbac\ufbad\ufee9\ufeea\ufeeb"
        "\ufeec\uff10\uff2f\uff4f\uffb7\U00010292\U000102ab\U0001030f\U00010404"
        "\U0001042c\U000104c2\U000104ea\U00010516\U0001092c\U00010c17\U00010d07"
        "\U00011124\U00011302\U000114d0\U000118b5\U000118c8\U000118d7\U000118e0"
        "\U00011de0\U00016ae9\U0001cce4\U0001ccf0\U0001d40e\U0001d428\U0001d442"
        "\U0001d45c\U0001d476\U0001d490\U0001d4aa\U0001d4de\U0001d4f8\U0001d512"
        "\U0001d52c\U0001d546\U0001d560\U0001d57a\U0001d594\U0001d5ae\U0001d5c8"
        "\U0001d5e2\U0001d5fc\U0001d616\U0001d630\U0001d64a\U0001d664\U0001d67e"
        "\U0001d698\U0001d6b6\U0001d6d0\U0001d6d4\U0001d6f0\U0001d70a\U0001d70e"
        "\U0001d72a\U0001d744\U0001d748\U0001d764\U0001d77e\U0001d782\U0001d79e"
        "\U0001d7b8\U0001d7bc\U0001d7ce\U0001d7d8\U0001d7e2\U0001d7ec\U0001d7f6"
        "\U0001e140\U0001e2f0\U0001ee24\U0001ee84\U0001f13e\U0001fbf0"
    ),
    "p": (
        "\u00fe\u01bf\u03a1\u03c1\u03f1\u03f8\u0420\u0440\u13e2\u146d\u1d18\u1d29"
        "\u1d3e\u1d56\u1e54\u1e55\u1e56\u1e57\u209a\u2119\u2374\u24c5\u24df\u2ca2"
        "\u2ca3\u2cce\u2ccf\ua4d1\uabb2\uff30\uff50\U00010295\U0001cce5\U0001d40f"
        "\U0001d429\U0001d443\U0001d45d\U0001d477\U0001d491\U0001d4ab\U0001d4c5"
        "\U0001d4df\U0001d4f9\U0001d513\U0001d52d\U0001d561\U0001d57b\U0001d595"
        "\U0001d5af\U0001d5c9\U0001d5e3\U0001d5fd\U0001d617\U0001d631\U0001d64b"
        "\U0001d665\U0001d67f\U0001d699\U0001d6b8\U0001d6d2\U0001d6e0\U0001d6f2"
        "\U0001d70c\U0001d71a\U0001d72c\U0001d746\U0001d754\U0001d766\U0001d780"
        "\U0001d78e\U0001d7a0\U0001d7ba\U0001d7c8\U0001f13f"
    ),
    "q": (
        "\u051a\u051b\u0563\u0566\u211a\u24c6\u24e0\u2d55\ua7af\ua7f4\uff31\uff51"
        "\U000107a5\U0001cce6\U0001d410\U0001d42a\U0001d444\U0001d45e\U0001d478"
        "\U0001d492\U0001d4ac\U0001d4c6\U0001d4e0\U0001d4fa\U0001d514\U0001d52e"
        "\U0001d562\U0001d57c\U0001d596\U0001d5b0\U0001d5ca\U0001d5e4\U0001d5fe"
        "\U0001d618\U0001d632\U0001d64c\U0001d666\U0001d680\U0001d69a\U0001f140"
    ),
    "r": (
        "\u0154\u0155\u0156\u0157\u0158\u0159\u01a6\u0210\u0211\u0212\u0213\u024c"
        "\u0280\u02b3\u0433\u13a1\u13d2\u1587\u1d26\u1d3f\u1d63\u1e58\u1e59\u1e5a"
        "\u1e5b\u1e5c\u1e5d\u1e5e\u1e5f\u211b\u211c\u211d\u24c7\u24e1\u2c85\ua4e3"
        "\uab47\uab48\uab71\uab81\uaba2\uff32\uff52\U000104b4\U000107aa\U00016a19"
        "\U00016f35\U0001cce7\U0001d216\U0001d411\U0001d42b\U0001d445\U0001d45f"
        "\U0001d479\U0001d493\U0001d4c7\U0001d4e1\U0001d4fb\U0001d52f\U0001d563"
        "\U0001d57d\U0001d597\U0001d5b1\U0001d5cb\U0001d5e5\U0001d5ff\U0001d619"
        "\U0001d633\U0001d64d\U0001d667\U0001d681\U0001d69b\U0001f12c\U0001f141"
    ),
    "s": (
        "\u015a\u015b\u015c\u015d\u015e\u015f\u0160\u0161\u017f\u01bd\u0218\u0219"
        "\u02e2\u0405\u0455\u054f\u0d1f\u10bd\u10fd\u13d5\u13da\u1cbd\u1e60\u1e61"
        "\u1e62\u1e63\u1e64\u1e65\u1e66\u1e67\u1e68\u1e69\u1e9b\u209b\u24c8\u24e2"
        "\ua4e2\ua576\ua731\uabaa\uff33\uff53\U00010296\U00010420\U00010448"
        "\U000118c1\U00016ad6\U00016f3a\U0001cce8\U0001d412\U0001d42c\U0001d446"
        "\U0001d460\U0001d47a\U0001d494\U0001d4ae\U0001d4c8\U0001d4e2\U0001d4fc"
        "\U0001d516\U0001d530\U0001d54a\U0001d564\U0001d57e\U0001d598\U0001d5b2"
        "\U0001d5cc\U0001d5e6\U0001d600\U0001d61a\U0001d634\U0001d64e\U0001d668"
        "\U0001d682\U0001d69c\U0001f142"
    ),
    "t": (
        "\u0162\u0163\u0164\u0165\u021a\u021b\u03a4\u03c4\u0422\u0442\u07e0\u13a2"
        "\u1c84\u1c85\u1d1b\u1d40\u1d57\u1e6a\u1e6b\u1e6c\u1e6d\u1e6e\u1e6f\u1e70"
        "\u1e71\u1e97\u209c\u22a4\u24c9\u24e3\u27d9\u2ca6\u2ca7\u3112\u4e05\ua4d4"
        "\ua50b\ua68d\uab72\uff34\uff54\U00010297\U000102b1\U00010315\U000118bc"
        "\U00016f0a\U0001cce9\U0001d373\U0001d413\U0001d42d\U0001d447\U0001d461"
        "\U0001d47b\U0001d495\U0001d4af\U0001d4c9\U0001d4e3\U0001d4fd\U0001d517"
        "\U0001d531\U0001d54b\U0001d565\U0001d57f\U0001d599\U0001d5b3\U0001d5cd"
        "\U0001d5e7\U0001d601\U0001d61b\U0001d635\U0001d64f\U0001d669\U0001d683"
        "\U0001d69d\U0001d6bb\U0001d6d5\U0001d6f5\U0001d70f\U0001d72f\U0001d749"
        "\U0001d769\U0001d783\U0001d7a3\U0001d7bd\U0001e040\U0001f143\U0001f768"
    ),
    "u": (
        "\u00d9\u00da\u00db\u00dc\u00f9\u00fa\u00fb\u00fc\u0168\u0169\u016a\u016b"
        "\u016c\u016d\u016e\u016f\u0170\u0171\u0172\u0173\u01af\u01b0\u01d3\u01d4"
        "\u01d5\u01d6\u01d7\u01d8\u01d9\u01da\u01db\u01dc\u0214\u0215\u0216\u0217"
        "\u028b\u03c5\u054d\u057d\u1200\u144c\u1d1c\u1d41\u1d58\u1d64\u1e72\u1e73"
        "\u1e74\u1e75\u1e76\u1e77\u1e78\u1e79\u1e7a\u1e7b\u1ee4\u1ee5\u1ee6\u1ee7"
        "\u1ee8\u1ee9\u1eea\u1eeb\u1eec\u1eed\u1eee\u1eef\u1ef0\u1ef1\u222a\u22c3"
        "\u24ca\u24e4\ua4f4\ua79f\uab4e\uab52\uff35\uff55\U000104ce\U000104f6"
        "\U000118b8\U000118d8\U00016f42\U0001ccea\U0001d414\U0001d42e\U0001d448"
        "\U0001d462\U0001d47c\U0001d496\U0001d4b0\U0001d4ca\U0001d4e4\U0001d4fe"
        "\U0001d518\U0001d532\U0001d54c\U0001d566\U0001d580\U0001d59a\U0001d5b4"
        "\U0001d5ce\U0001d5e8\U0001d602\U0001d61c\U0001d636\U0001d650\U0001d66a"
        "\U0001d684\U0001d69e\U0001d6d6\U0001d710\U0001d74a\U0001d784\U0001d7be"
        "\U0001f144"
    ),
    "v": (
        "\u03bd\u0474\u0475\u05d8\u0667\u06f7\u13d9\u142f\u1d20\u1d5b\u1d65\u1e7c"
        "\u1e7d\u1e7e\u1e7f\u2164\u2174\u2228\u22c1\u24cb\u24e5\u2c7d\u2d38\ua4e6"
        "\ua6df\uaba9\uff36\uff56\U0001051d\U00010c1f\U00011706\U000118a0"
        "\U000118c0\U00016f08\U0001cceb\U0001cefc\U0001d20d\U0001d415\U0001d42f"
        "\U0001d449\U0001d463\U0001d47d\U0001d497\U0001d4b1\U0001d4cb\U0001d4e5"
        "\U0001d4ff\U0001d519\U0001d533\U0001d54d\U0001d567\U0001d581\U0001d59b"
        "\U0001d5b5\U0001d5cf\U0001d5e9\U0001d603\U0001d61d\U0001d637\U0001d651"
        "\U0001d66b\U0001d685\U0001d69f\U0001d6ce\U0001d708\U0001d742\U0001d77c"
        "\U0001d7b6\U0001e145\U0001f145"
    ),
    "w": (
        "\u0174\u0175\u026f\u02b7\u0448\u0461\u051c\u051d\u0561\u13b3\u13d4\u1d21"
        "\u1d42\u1e80\u1e81\u1e82\u1e83\u1e84\u1e85\u1e86\u1e87\u1e88\u1e89\u1e98"
        "\u24cc\u24e6\u29e2\u2cbd\ua4ea\ua7fa\uab83\uaba4\uff37\uff57\U0001170a"
        "\U0001170e\U0001170f\U000118e6\U000118ef\U0001ccec\U0001d20c\U0001d416"
        "\U0001d430\U0001d44a\U0001d464\U0001d47e\U0001d498\U0001d4b2\U0001d4cc"
        "\U0001d4e6\U0001d500\U0001d51a\U0001d534\U0001d54e\U0001d568\U0001d582"
        "\U0001d59c\U0001d5b6\U0001d5d0\U0001d5ea\U0001d604\U0001d61e\U0001d638"
        "\U0001d652\U0001d66c\U0001d686\U0001d6a0\U0001df7d\U0001f146"
    ),
    "x": (
        "\u00d7\u02e3\u03a7\u03c7\u0425\u0445\u1541\u157d\u166d\u166e\u16b7\u1763"
        "\u1bec\u1cf5\u1d61\u1d6a\u1e8a\u1e8b\u1e8c\u1e8d\u2093\u2169\u2179\u24cd"
        "\u24e7\u2573\u292b\u292c\u2a2f\u2cac\u2cad\u2d5d\ua4eb\ua7b3\uab53\uab55"
        "\uff38\uff58\U00010290\U000102b4\U00010317\U00010322\U00010527\U00010c13"
        "\U00010c82\U00010cc2\U00010cfc\U000118ec\U0001cced\U0001d417\U0001d431"
        "\U0001d44b\U0001d465\U0001d47f\U0001d499\U0001d4b3\U0001d4cd\U0001d4e7"
        "\U0001d501\U0001d51b\U0001d535\U0001d54f\U0001d569\U0001d583\U0001d59d"
        "\U0001d5b7\U0001d5d1\U0001d5eb\U0001d605\U0001d61f\U0001d639\U0001d653"
        "\U0001d66d\U0001d687\U0001d6a1\U0001d6be\U0001d6d8\U0001d6f8\U0001d712"
        "\U0001d732\U0001d74c\U0001d76c\U0001d786\U0001d7a6\U0001d7c0\U0001f147"
    ),
    "y": (
        "\u00dd\u00fd\u00ff\u0176\u0177\u0178\u0232\u0233\u0263\u028f\u02b8\u03a5"
        "\u03b3\u03d2\u0423\u0443\u04ae\u04af\u07cc\u10e7\u13a9\u13bd\u1d8c\u1e8e"
        "\u1e8f\u1e99\u1ef2\u1ef3\u1ef4\u1ef5\u1ef6\u1ef7\u1ef8\u1ef9\u1eff\u213d"
        "\u24ce\u24e8\u2ca8\u2ca9\u311a\u4e2b\ua4ec\uab5a\uff39\uff59\U000102b2"
        "\U00010c20\U000118a4\U000118c4\U000118dc\U00016f43\U0001ccee\U0001d418"
        "\U0001d432\U0001d44c\U0001d466\U0001d480\U0001d49a\U0001d4b4\U0001d4ce"
        "\U0001d4e8\U0001d502\U0001d51c\U0001d536\U0001d550\U0001d56a\U0001d584"
        "\U0001d59e\U0001d5b8\U0001d5d2\U0001d5ec\U0001d606\U0001d620\U0001d63a"
        "\U0001d654\U0001d66e\U0001d688\U0001d6a2\U0001d6bc\U0001d6c4\U0001d6f6"
        "\U0001d6fe\U0001d730\U0001d738\U0001d76a\U0001d772\U0001d7a4\U0001d7ac"
        "\U0001f148"
    ),
    "z": (
        "\u0179\u017a\u017b\u017c\u017d\u017e\u0396\u10cd\u13c3\u1d22\u1dbb\u1e90"
        "\u1e91\u1e92\u1e93\u1e94\u1e95\u2124\u2128\u24cf\u24e9\u2c6b\u2c6c\u2c8c"
        "\u2c8d\u2d2d\ua4dc\ua6c9\uab93\uff3a\uff5a\U000102f5\U00010507\U000118a9"
        "\U000118e5\U00011abc\U0001ccef\U0001d419\U0001d433\U0001d44d\U0001d467"
        "\U0001d481\U0001d49b\U0001d4b5\U0001d4cf\U0001d4e9\U0001d503\U0001d537"
        "\U0001d56b\U0001d585\U0001d59f\U0001d5b9\U0001d5d3\U0001d5ed\U0001d607"
        "\U0001d621\U0001d63b\U0001d655\U0001d66f\U0001d689\U0001d6a3\U0001d6ad"
        "\U0001d6e7\U0001d721\U0001d75b\U0001d795\U0001f149"
    ),
}
"""For each target, the characters that read as it, in code point order."""

SEQUENCES: dict[str, str] = {
    "10": ("\u2469"),
    "11": ("\u246a"),
    "12": ("\u246b"),
    "13": ("\u246c"),
    "14": ("\u246d"),
    "15": ("\u246e"),
    "16": ("\u246f"),
    "17": ("\u2470"),
    "18": ("\u2471"),
    "19": ("\u2472"),
    "20": ("\u2473"),
    "21": ("\u3251"),
    "22": ("\u3252"),
    "23": ("\u3253"),
    "24": ("\u3254"),
    "25": ("\u3255"),
    "26": ("\u3256"),
    "27": ("\u3257"),
    "28": ("\u3258"),
    "29": ("\u3259"),
    "30": ("\u325a"),
    "31": ("\u325b"),
    "32": ("\u325c"),
    "33": ("\u325d"),
    "34": ("\u325e"),
    "35": ("\u325f"),
    "36": ("\u32b1"),
    "37": ("\u32b2"),
    "38": ("\u32b3"),
    "39": ("\u32b4"),
    "40": ("\u32b5"),
    "41": ("\u32b6"),
    "42": ("\u32b7"),
    "43": ("\u32b8"),
    "44": ("\u32b9"),
    "45": ("\u32ba"),
    "46": ("\u32bb"),
    "47": ("\u32bc"),
    "48": ("\u32bd"),
    "49": ("\u32be"),
    "50": ("\u32bf"),
    "aa": ("\ua732\ua733"),
    "ae": ("\u00c6\u00e6\u04d4\u04d5"),
    "ao": ("\ua734\ua735"),
    "ar": ("\U0001f707"),
    "au": ("\u3373\ua736\ua737"),
    "av": ("\ua738\ua739\ua73a\ua73b"),
    "ay": ("\ua73c\ua73d"),
    "bar": ("\u3374"),
    "bl": ("\u042b"),
    "bq": ("\u33c3"),
    "cal": ("\u3388"),
    "cc": ("\u33c4"),
    "cd": ("\u33c5\U0001f12d"),
    "cm": ("\u339d"),
    "cm2": ("\u33a0"),
    "cm3": ("\u33a4"),
    "co": ("\uab43"),
    "crn": ("\u339d"),
    "da": ("\u3372"),
    "db": ("\u33c8"),
    "dj": ("\U0001f190"),
    "dl": ("\u3397"),
    "dm": ("\u3377"),
    "dm2": ("\u3378"),
    "dm3": ("\u3379"),
    "drn": ("\u3377"),
    "dz": ("\u01f1\u01f2\u01f3\u02a3"),
    "erg": ("\u32cd"),
    "ev": ("\u32ce"),
    "fax": ("\u213b"),
    "ff": ("\ufb00"),
    "ffi": ("\ufb03"),
    "ffl": ("\ufb04"),
    "fi": ("\ufb01"),
    "fl": ("\ufb02"),
    "fm": ("\u3399"),
    "frn": ("\u3399"),
    "ft": ("\ufb05"),
    "gal": ("\u33ff"),
    "gb": ("\u3387"),
    "ghz": ("\u3393"),
    "gpa": ("\u33ac"),
    "gy": ("\u33c9"),
    "ha": ("\u33ca"),
    "hg": ("\u32cc"),
    "hp": ("\u33cb"),
    "hpa": ("\u3371"),
    "hv": ("\U0001f14a"),
    "hz": ("\u3390"),
    "ie": ("\U0001df5d"),
    "ii": ("\u2161\u2171"),
    "iii": ("\u2162\u2172"),
    "ij": ("\u0132\u0133"),
    "in": ("\u33cc"),
    "iu": ("\u337a"),
    "iv": ("\u2163\u2173"),
    "ix": ("\u2168\u2178"),
    "ka": ("\u3384"),
    "kb": ("\u3385"),
    "kcal": ("\u3389"),
    "kg": ("\u338f"),
    "khz": ("\u3391"),
    "kk": ("\u33cd"),
    "kl": ("\u3398"),
    "km": ("\u339e\u33ce"),
    "km2": ("\u33a2"),
    "km3": ("\u33a6"),
    "kpa": ("\u33aa"),
    "krn": ("\u339e"),
    "kt": ("\u33cf"),
    "kv": ("\u33b8"),
    "kw": ("\u33be"),
    "lj": ("\u0132\u01c7\u01c8\u01c9"),
    "ll": (
        "\u01c1\u05f0\u0965\u104b\u1efa\u2016\u2161\u2225\ua8cf\U00011048"
        "\U000110c1\U00011142\U000111c6\U000113d5\U0001144c\U00011642\U00011c42"
        "\U0001d262"
    ),
    "lll": ("\u2162\ua516"),
    "lm": ("\u33d0"),
    "ln": ("\u33d1"),
    "lo": ("\u042e"),
    "log": ("\u33d2"),
    "lrn": ("\u33d0"),
    "ls": ("\u02aa"),
    "lt": ("\u20b6"),
    "ltd": ("\u32cf"),
    "lu": ("\u337a"),
    "lv": ("\u2163"),
    "lx": ("\u2168\u33d3"),
    "lz": ("\u02ab"),
    "m2": ("\u33a1"),
    "m3": ("\u33a5"),
    "ma": ("\u3383"),
    "mb": ("\u3386\u33d4\U0001f76b"),
    "mc": ("\U0001f16a"),
    "md": ("\U0001f16b"),
    "mg": ("\u338e"),
    "mhz": ("\u3392"),
    "mil": ("\u33d5"),
    "ml": ("\u3396"),
    "mm": ("\u339c"),
    "mm2": ("\u339f"),
    "mm3": ("\u33a3"),
    "mol": ("\u33d6"),
    "mpa": ("\u33ab"),
    "mr": ("\U0001f16c"),
    "ms": ("\u33b3"),
    "mv": ("\u33b7\u33b9\U0001f14b"),
    "mw": ("\u33bd\u33bf"),
    "na": ("\u3381"),
    "nf": ("\u338b"),
    "nj": ("\u01ca\u01cb\u01cc"),
    "nm": ("\u339a"),
    "no": ("\u2116"),
    "nrn": ("\u339a"),
    "ns": ("\u33b1"),
    "nv": ("\u33b5"),
    "nw": ("\u33bb"),
    "oe": ("\u0152\u0153"),
    "oi": ("\U0001df5e"),
    "ol": ("\U0001ee64"),
    "oo": ("\u1147\u11ee\u221e\u3180\ua698\ua699\ua74e\ua74f"),
    "ou": ("\U0001df5f"),
    "ov": ("\u3375"),
    "oy": ("\u0478\u0479"),
    "pa": ("\u3380\u33a9"),
    "pc": ("\u3376"),
    "pf": ("\u338a"),
    "ph": ("\u33d7"),
    "ppm": ("\u33d9"),
    "ppv": ("\U0001f14e"),
    "pr": ("\u33da"),
    "ps": ("\u33b0"),
    "pte": ("\u3250"),
    "pv": ("\u33b4"),
    "pw": ("\u33ba"),
    "qe": ("\U0001f700"),
    "rad": ("\u33ad"),
    "rn": (
        "\u0560\u217f\uff4d\U00011700\U000118e3\U0001d426\U0001d45a\U0001d48e"
        "\U0001d4c2\U0001d4f6\U0001d52a\U0001d55e\U0001d592\U0001d5c6\U0001d5fa"
        "\U0001d62e\U0001d662\U0001d696"
    ),
    "rna": ("\u3383"),
    "rnb": ("\u33d4"),
    "rng": ("\u338e"),
    "rnil": ("\u33d5"),
    "rnl": ("\u3396"),
    "rnol": ("\u33d6"),
    "rnrn": ("\u339c"),
    "rns": ("\u33b3"),
    "rnv": ("\u33b7"),
    "rnw": ("\u33bd"),
    "rs": ("\u20a8"),
    "sd": ("\U0001f14c"),
    "sm": ("\u2120"),
    "sr": ("\u33db"),
    "ss": ("\u00df\u1e9e\U0001f14d"),
    "sss": ("\U0001f75c"),
    "st": ("\ufb05\ufb06"),
    "sv": ("\u33dc"),
    "t3": ("\ua728"),
    "tel": ("\u2121"),
    "tf": ("\ua777"),
    "th": ("\U0001df64"),
    "thz": ("\u3394"),
    "tm": ("\u2122"),
    "ts": ("\u02a6"),
    "ue": ("\u1d6b"),
    "uo": ("\uab63"),
    "vb": ("\U0001f76c"),
    "vi": ("\u2165\u2175"),
    "vii": ("\u2166\u2176"),
    "viii": ("\u2167\u2177"),
    "vl": ("\u2165"),
    "vll": ("\u2166"),
    "vlll": ("\u2167"),
    "wb": ("\u33dd"),
    "wc": ("\U0001f14f"),
    "wh": ("\U0001df65"),
    "wz": ("\U0001f12e"),
    "xi": ("\u216a\u217a"),
    "xii": ("\u216b\u217b"),
    "xl": ("\u216a"),
    "xll": ("\u216b"),
}
"""For each run of two to four letters, the characters that read as it."""
